package de.htwg.se.monopoly.model

enum Street_Names:
  case Schlossallee
  case Bahnhofstrasse
  case Parkstrasse
  case Seestrasse
  case Hafenstrasse
  case Chausseestrasse
  case Elisenstrasse
  case Opernplatz
  case Theaterplatz
  case Badstrasse
  case Turmstrasse
  case Goethestrasse
  case Rathausplatz
  case Poststrasse
  case Hauptstrasse
  case Kirchplatz
  case Ringstrasse
  case Schillerstrasse
  case Bismarckstrasse
  case Goetheplatz
  case Kaiserstrasse
  case Lessingstrasse
  case Wilhelmstrasse
  case Auguststrasse
  case Friedrichstrasse
  case Bergstrasse
  case Kurfurstendamm
  case Alexanderplatz
  case Breitscheidplatz
  case Friedrichshain
  case Schoneberg
  case Charlottenburg
  case Wedding
  case Kreuzberg
  case Neukolln
  case Spandau
  case Tempelhof
  case Wilmersdorf
  case Mitte
  case Steglitz
  case Tiergarten
  case Lichtenberg
  case Reinickendorf
  case Marzahn
  case Hellersdorf
  case Treptow
  case   Moabit
  case Kopenick
  case Zehlendorf
  case Friedenau
  case Pankow
  case Adlershof
  case Hohenschonhausen
  case Grunewald
  case Rummelsburg
  case Nikolassee
  case Gesundbrunnen
  case Britz
  case Weissensee
  case Fennpfuhl
  case Mahlsdorf
  case Buch
  case Wilhelmstadt
  case Karow
  case Falkenberg
  case Heinersdorf
  case   Baumschulenweg
  case Rahnsdorf
  case Borsigwalde
  case Rosenthal
  case Karolinenhof
  case Buchholz
  case Kolln
  case Schmockwitz
  case Schmargendorf
  case Kaulsdorf
  case Lankwitz
  case Niederschoneweide
  case Frohnau
  case Altglienicke
  case Friedrichsfelde
  case Bohnsdorf
  case Karlshorst
  case Planterwald
  case Wartenberg
  case Kladow